# encoding: utf-8
#
# Copyright (C) 2011-2012  AdMaster, Inc.

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "thin"
gem "json"
gem "rake"
gem "mongoid"
gem "bson_ext"
gem "apimaster"

group :development do
end

group :production do
end

group :test do
  gem "rack-test"
end
